[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=BAMapi --cov=tests --cov-fail-under=80 --cov-report=xml"
testpaths = [
    "tests",
]